package GUI;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.media.j3d.Canvas3D;
import javax.swing.JDialog;
import javax.swing.JFrame;

public class Visualization extends javax.swing.JFrame {

    public Visualization(Canvas3D canvas) {
        initComponents();
        
        // Varios atributos de la ventana
        setTitle("Practica 1 - Sistema solar");
        setSize(700, 700);
        setLocation (100, 100);
        
        // Se le inserta el canvas
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(canvas, BorderLayout.CENTER);
        repaint();
    }
    
    private Control controlWindow;

    public Visualization (Canvas3D canvas, Control parent, boolean modal) { 
        //super((JFrame) null, modal);
        initComponents();
        // Referencia a su ventana de control
        controlWindow = parent;
        // Varios atributos de la ventana
        setTitle("Practica 1 - Sistema solar");
        setSize(700, 700);
        setLocation(100, 100);
        // Se le inserta el canvas
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(canvas, BorderLayout.CENTER);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
